project:
  type: website

website:
  title: "Quarto Portfolio Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/
        text: Workshop Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



